### ISSUE TITLE
Parsing Requirements from Events is currently failing silently due to hitting Unreachable().

### ISSUE THREAD

**Issue by jeremydk** [progre/lmorandomizer#23]
There's a silent failure which kills the tokio runtime worker, leading incorrectly to the appearance of a seed being generated unless you're running from a terminal with RUST_BACKTRACE set.

https://github.com/progre/lmorandomizer/blob/3dfc9d3acfeeb249c751d9dd0e9f50012e403039/src-tauri/src/dataset/supplements.rs#L189

**Comment by progre** [comment]
Thanks for checking.

I don't think it was occurring in my environment.
If there is any error information being output, that would help me fix it.
However, I am planning a major rewrite of the current code, so it may be fixed in the process.

**Comment by progre** [comment]
Thanks for checking.

Maybe such a problem occurs with certain seeds.
We are planning a major rewrite of the current code, so this may be fixed in the process.

**Comment by jeremydk** [comment]
I've been unable to find a working seed.  Currently repro with seed `1`

```
thread 'tokio-runtime-worker' panicked at src/dataset/supplements.rs:226:5:
internal error: entered unreachable code
stack backtrace:
   0:        0x101455cd0 - std::backtrace_rs::backtrace::libunwind::trace::hadefa2fe489b32be
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:        0x101455cd0 - std::backtrace_rs::backtrace::trace_unsynchronized::h37e8bb3c3fd9c67c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x101455cd0 - std::sys_common::backtrace::_print_fmt::h4994a90b70e9aaa7
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:        0x101455cd0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb478ebbfb46e27ce
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1014760f8 - core::fmt::rt::Argument::fmt::hfe2e626e52db21d5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:        0x1014760f8 - core::fmt::write::he4d5fa2daff1f531
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:        0x101452ed0 - std::io::Write::write_fmt::hc5a47a68eba63d9f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:        0x101455b04 - std::sys_common::backtrace::_print::hd47355bf70e1c2da
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x101455b04 - std::sys_common::backtrace::print::h79bd952cc5812e7a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x101457228 - std::panicking::default_hook::{{closure}}::h82301f6222887737
  10:        0x101456f70 - std::panicking::default_hook::h1e49abbb3f1d7dbf
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:        0x101457670 - std::panicking::rust_panic_with_hook::h1e70c5d905e30e9d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:        0x101457538 - std::panicking::begin_panic_handler::{{closure}}::h399e32952efd26a4
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:649:13
  13:        0x101456154 - std::sys_common::backtrace::__rust_end_short_backtrace::h2ab87f841a2323e7
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:        0x1014572ec - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:        0x1014a084c - core::panicking::panic_fmt::h33e40d2a93cab78f
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:        0x1014a08d4 - core::panicking::panic::h57fd475c037a9df3
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
  17:        0x100f5e8dc - lmorandomizer::dataset::supplements::Supplements::new::hdcc5d74fa769a369
  18:        0x100f9d744 - lmorandomizer::randomizer::randomize::ha83293a1b063b8c7
  19:        0x101064a48 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h3e2b0dd2ea14263e
  20:        0x100fa9a94 - tauri::ipc::InvokeResolver<R>::respond_async_serialized::{{closure}}::h0dfe9ff8282d71bf
  21:        0x100fd1118 - tokio::runtime::task::core::Core<T,S>::poll::hfdd39ced09254417
  22:        0x100eff368 - tokio::runtime::task::harness::Harness<T,S>::poll::hd0bfeb3e7a144d27
  23:        0x101320f4c - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h80a751673cae1d0d
  24:        0x10131fbb0 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hfdd4a0e976fa0fa0
  25:        0x101315848 - tokio::runtime::context::set_scheduler::hd71ca6fcb7b82b39
  26:        0x1013251a0 - tokio::runtime::context::runtime::enter_runtime::hfe81e61dff08a1f6
  27:        0x10131f9e4 - tokio::runtime::scheduler::multi_thread::worker::run::h5394882422110d0c
  28:        0x10132b8d4 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h3bca4e38d4544119
  29:        0x1013197b0 - tokio::runtime::task::core::Core<T,S>::poll::h864a9cd8f088050f
  30:        0x101311598 - tokio::runtime::task::harness::Harness<T,S>::poll::h23cc3d7c7fff0772
  31:        0x10132b02c - tokio::runtime::blocking::pool::Inner::run::he02d064570d8d656
  32:        0x101326888 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1e1fcef1638ef565
  33:        0x1013144a8 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h35cd0f99d43a06fc
  34:        0x10145b9c0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h122931d29f919766
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  35:        0x10145b9c0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h222f385c86e71c13
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/alloc/src/boxed.rs:2015:9
  36:        0x10145b9c0 - std::sys::unix::thread::Thread::new::thread_start::h8dda2af345bab446
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys/unix/thread.rs:108:17
  37:        0x1974aef94 - __pthread_joiner_wake
  ```

**Comment by progre** [comment]
Unfortunately, it did not reproduce on my end.
SHA2-224 of created script.dat `FC94E9F4120EDB97F75C90A5DBE07E914DBD1D2546A41688ED31C2C4`

There may still be unpredictable problems, so please wait a little longer.
I'm also going to replace the shuffle function. It includes code using f64 ported from JavaScript.

**Comment by progre** [comment]
The latest data update was not pushed. I just now pushed it. Now you should get different results with the same seed.

**Comment by jeremydk** [comment]
Just tried off of `main` and succeeded with seed generation.

Thanks!
